import java.util.Arrays;

public class Minibus extends Vehicle{
    public Minibus(String outputFile, int voyageId, String voyageFrom, String voyageTo, int seatRows, float standardSeatPrice) {
        super(voyageId, voyageFrom, voyageTo, seatRows, standardSeatPrice);
        this.availableSeats = new boolean[numberOfStandardSeats(seatRows)];
        Arrays.fill(availableSeats, true); // Set all seats available initially.

        FileOutput.writeToFile(outputFile, "Voyage " + voyageId + " was initialized as a minibus (2) voyage from " + voyageFrom + " to " +
                voyageTo + " with " + String.format("%.2f", standardSeatPrice).replace(",", ".") + " TL priced " +
                numberOfStandardSeats(seatRows) + " regular seats. Note that minibus tickets are not refundable.", true, true);
    }

    protected int numberOfStandardSeats(int seatRows) {
        return seatRows * 2;
    }

    /**
     * Displays information about the vehicle and its seats, including available and booked seats,
     * and revenue generated by the vehicle, and writes this information to the specified output file.
     *
     * @param outputFile The path of the output file where the vehicle information will be written.
     */
    public void displayVehicle(String outputFile) {
        FileOutput.writeToFile(outputFile, "Voyage " + voyageId, true, true);
        FileOutput.writeToFile(outputFile, voyageFrom + "-" + voyageTo, true, true);

        for (int row = 0; row < seatRows; row++) {
            for (int seat = 0; seat < 2; seat++) {
                int index = row * 2 + seat;
                if (index < availableSeats.length) {
                    if (availableSeats[index]) {
                        FileOutput.writeToFile(outputFile, "*", true, false);
                    } else {
                        FileOutput.writeToFile(outputFile, "X", true, false);
                    }
                    // Add space if it's not the last seat in the row
                    if (seat == 0) {
                        FileOutput.writeToFile(outputFile, " ", true, false);
                    }
                }
            }
            FileOutput.writeToFile(outputFile, "", true, true); // Move to the next row
        }
        FileOutput.writeToFile(outputFile, "Revenue: " + String.format("%.2f", revenue).replace(",", "."), true, true);
    }
}