import java.util.*;

public class PremiumBus extends Vehicle{
    protected int refundCut;
    protected int premiumFee;
    protected int numberOfPremiumSeats;
    protected float premiumSeatPrice;
    protected float refundedStandardSeatPrice;
    protected float refundedPremiumSeatPrice;
    protected boolean[] premiumSeats;

    public PremiumBus(String outputFile, int voyageId, String voyageFrom, String voyageTo, int seatRows, float standardSeatPrice, int refundCut, int premiumFee) {
        super(voyageId, voyageFrom, voyageTo, seatRows, standardSeatPrice);
        this.refundCut = refundCut;
        this.premiumFee = premiumFee;
        this.numberOfPremiumSeats = numberOfPremiumSeats(seatRows); // Calculate and set numberOfPremiumSeats.
        this.premiumSeatPrice = premiumSeatPrice(standardSeatPrice, premiumFee); // Calculate and set premiumSeatPrice.
        this.refundedStandardSeatPrice = refundedSeatPrice(standardSeatPrice, refundCut); // Calculate and set refundedStandardSeatPrice.
        this.refundedPremiumSeatPrice = refundedSeatPrice(premiumSeatPrice, refundCut); // Calculate and set refundedPremiumSeatPrice.
        this.availableSeats = new boolean[numberOfStandardSeats(seatRows) + numberOfPremiumSeats(seatRows)];
        Arrays.fill(availableSeats, true); // Set all seats available initially.
        this.premiumSeats = new boolean[numberOfStandardSeats(seatRows) + numberOfPremiumSeats(seatRows)];
        initializePremiumSeats(premiumSeats); // Set the seats according to whether they are premium or not.

        FileOutput.writeToFile(outputFile, "Voyage " + voyageId + " was initialized as a premium (1+2) voyage from " + voyageFrom + " to " + voyageTo +
                " with " + String.format("%.2f", standardSeatPrice).replace(",", ".") + " TL priced " + numberOfStandardSeats(seatRows) +
                " regular seats and " + String.format("%.2f", premiumSeatPrice(standardSeatPrice, premiumFee)).replace(",", ".") + " TL priced " +
                numberOfPremiumSeats(seatRows) + " premium seats. Note that refunds will be " + refundCut + "% less than the paid amount.", true, true);
    }

    public float getPremiumSeatPrice() {
        return premiumSeatPrice;
    }

    public float getRefundedStandardSeatPrice() {
        return refundedStandardSeatPrice;
    }

    public float getRefundedPremiumSeatPrice() {
        return refundedPremiumSeatPrice;
    }

    protected int numberOfStandardSeats(int seatRows) {
        return seatRows * 2;
    }

    protected int numberOfPremiumSeats(int seatRows) {
        return seatRows;
    }

    /**
     * Calculates the price for a premium seat based on the standard seat price and premium fee.
     *
     * @param standardSeatPrice The standard price for a seat.
     * @param premiumFee        The premium fee as a percentage of the standard seat price.
     * @return                  The price for a premium seat.
     */
    protected float premiumSeatPrice(float standardSeatPrice, int premiumFee) {
        float increaseRate = (float) premiumFee / 100;
        return standardSeatPrice * (1 + increaseRate);
    }

    /**
     * Calculates the refunded price for a seat based on the original seat price and refund cut percentage.
     *
     * @param seatPrice The original price of the seat.
     * @param refundCut The refund cut as a percentage of the original seat price.
     * @return          The refunded price for the seat.
     */
    protected float refundedSeatPrice(float seatPrice, int refundCut) {
        float refundAmount = seatPrice * ((float) refundCut / 100);
        return seatPrice - refundAmount;
    }

    /**
     * Initializes the premium seats array, marking every third seat as premium.
     *
     * @param premiumSeats The boolean array representing premium seats.
     */
    protected void initializePremiumSeats(boolean[] premiumSeats) {
        for (int seat = 0; seat < premiumSeats.length; seat++) {
            premiumSeats[seat] = (seat + 1) % 3 == 1;
        }
    }

    /**
     * Checks if a seat is a premium seat based on its seat number.
     *
     * @param seatNumber The seat number to be checked.
     * @return           True if the seat is premium, false otherwise.
     */
    public boolean isSeatPremium(int seatNumber) {
        if (seatNumber >= 1 && seatNumber <= premiumSeats.length) {
            return premiumSeats[seatNumber - 1];
        } else {
            System.out.println("ERROR: Invalid seat number.");
            return false;
        }
    }

    /**
     * Displays information about the vehicle and its seats, including available and booked seats,
     * and revenue generated by the vehicle, and writes this information to the specified output file.
     *
     * @param outputFile The path of the output file where the vehicle information will be written.
     */
    public void displayVehicle(String outputFile) {
        FileOutput.writeToFile(outputFile, "Voyage " + voyageId, true, true);
        FileOutput.writeToFile(outputFile, voyageFrom + "-" + voyageTo, true, true);

        for (int row = 0; row < seatRows; row++) {
            for (int seat = 0; seat < 3; seat++) {
                int index = row * 3 + seat;
                if (index < availableSeats.length) {
                    if (availableSeats[index]) {
                        FileOutput.writeToFile(outputFile, "*", true, false);
                    } else {
                        FileOutput.writeToFile(outputFile, "X", true, false);
                    }
                    // Add space if it's not the last seat in the row
                    if (seat == 1) {
                        FileOutput.writeToFile(outputFile, " ", true, false);
                    } else if (seat == 0) {
                        FileOutput.writeToFile(outputFile, " | ", true, false);
                    }
                }
            }
            FileOutput.writeToFile(outputFile, "", true, true); // Move to the next row
        }
        FileOutput.writeToFile(outputFile, "Revenue: " + String.format("%.2f", revenue).replace(",", "."), true, true);
    }
}
