import java.util.Arrays;

public class StandardBus extends Vehicle{
    protected int refundCut;
    protected float refundedStandardSeatPrice;

    public StandardBus(String outputFile, int voyageId, String voyageFrom, String voyageTo, int seatRows, float standardSeatPrice, int refundCut) {
        super(voyageId, voyageFrom, voyageTo, seatRows, standardSeatPrice);
        this.refundCut = refundCut;
        this.refundedStandardSeatPrice = refundedSeatPrice(standardSeatPrice, refundCut); // Calculate and set refundedStandardSeatPrice.
        this.availableSeats = new boolean[numberOfStandardSeats(seatRows)];
        Arrays.fill(availableSeats, true); // Set all seats available initially.

        FileOutput.writeToFile(outputFile, "Voyage " + voyageId + " was initialized as a standard (2+2) voyage from " + voyageFrom + " to " +
                voyageTo + " with " + String.format("%.2f", standardSeatPrice).replace(",", ".") + " TL priced " +
                numberOfStandardSeats(seatRows) + " regular seats. Note that refunds will be " + refundCut + "% less than the paid amount.", true, true);
    }

    public float getRefundedStandardSeatPrice() {
        return refundedStandardSeatPrice;
    }

    protected int numberOfStandardSeats(int seatRows) {
        return seatRows * 4;
    }


    /**
     * Calculates the refunded price for a seat based on the original seat price and refund cut percentage.
     *
     * @param seatPrice The original price of the seat.
     * @param refundCut The refund cut as a percentage of the original seat price.
     * @return          The refunded price for the seat.
     */
    protected float refundedSeatPrice(float seatPrice, int refundCut) {
        float refundAmount = seatPrice * ((float) refundCut / 100);
        return seatPrice - refundAmount;
    }

    /**
     * Displays information about the vehicle and its seats, including available and booked seats,
     * and revenue generated by the vehicle, and writes this information to the specified output file.
     *
     * @param outputFile The path of the output file where the vehicle information will be written.
     */
    public void displayVehicle(String outputFile) {
        FileOutput.writeToFile(outputFile, "Voyage " + voyageId, true, true);
        FileOutput.writeToFile(outputFile, voyageFrom + "-" + voyageTo, true, true);

        for (int row = 0; row < seatRows; row++) {
            for (int seat = 0; seat < 4; seat++) {
                int index = row * 4 + seat;
                if (index < availableSeats.length) {
                    if (availableSeats[index]) {
                        FileOutput.writeToFile(outputFile, "*", true, false);
                    } else {
                        FileOutput.writeToFile(outputFile, "X", true, false);
                    }
                    // Add space if it's not the last seat in the row
                    if (seat == 0 || seat == 2) {
                        FileOutput.writeToFile(outputFile, " ", true, false);
                    } else if (seat == 1) {
                        FileOutput.writeToFile(outputFile, " | ", true, false);
                    }
                }
            }
            FileOutput.writeToFile(outputFile, "", true, true); // Move to the next row
        }
        FileOutput.writeToFile(outputFile, "Revenue: " + String.format("%.2f", revenue).replace(",", "."), true, true);
    }
}

